enable aarch64 linux builds
conda-forge/libsimpleitk-feedstock pull request #21
Opened 2022-12-09 17:59 UTC by blowekamp

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-12-09 17:59 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-12-09 18:36 UTC, zivy requested changes

2022-12-09 18:36 UTC, zivy commented on conda-forge.yml
> +  enabled: trie
trie -> true

2022-12-09 21:24 UTC, zivy approved these changes

2023-07-11 20:02 UTC, blowekamp commented
@conda-forge-admin please rerender

2023-09-14 14:43 UTC, blowekamp commented
@conda-forge-admin please rerender

2023-09-14 16:58 UTC, blowekamp commented
@conda-forge-admin please rerender

2023-09-14 19:11 UTC, blowekamp commented
@conda-forge-admin please rerender

2023-09-15 14:22 UTC, blowekamp commented
@conda-forge-admin please rerender

2023-11-02 13:46 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-12 16:20 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-12 21:05 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-12 21:17 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-12 22:59 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-13 01:07 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-13 14:20 UTC, blowekamp commented
@conda-forge-admin please rerender

2024-08-13 17:33 UTC, hmaarrfk commented on recipe/meta.yaml
>      - libitk-devel  5.3.*
can we try to unpin this?

2024-08-14 20:38 UTC, blowekamp commented
closing for  #31

2024-08-14 20:38 UTC, closed without merging